### ISSUE TITLE
Build a To-Do List app with React

### ISSUE THREAD

**Issue by h3cksamrat** [cockroachdb/cockroachdb-todo-apps#22]
I would like to start this but need to learn about cockroachdb, never heard of it. Anyway, I'm gonna complete it.

**Comment by Amruta-Ranade** [comment]
Here are some resources to help you learn cockroachdb: 
https://www.cockroachlabs.com/cockroach-university/
https://www.cockroachlabs.com/docs/stable/

**Comment by hoangdqvn** [comment]
Please help me check my PR: https://github.com/cockroachdb/cockroachdb-todo-apps/pull/26

**Comment by mrswapnilsahu** [comment]
Hey @Amruta-Ranade  Can I work on this ?

**Comment by Amruta-Ranade** [comment]
Sure!

**Comment by vinayak0127** [comment]
Hey! can I work on this issue?

**Comment by Amruta-Ranade** [comment]
Go for it!
