### ISSUE TITLE
ASP.NET web API on its own or within the csharp TO-DO app?

### ISSUE THREAD

**Issue by mmutiso** [cockroachdb/cockroachdb-todo-apps#39]
Hi @Amruta-Ranade , kindly clarify here, I wanna do an ASP.NET core web api. Do you think it needs to go into [this C#](https://github.com/cockroachdb/cockroachdb-todo-apps/tree/master/csharp_ToDoApp_Matthew_Mutiso) one or on its own directory? 

I would vote for its own directory.

**Comment by Amruta-Ranade** [comment]
Let's think from a user's perspective -- if a user sees the main page of the repo (https://github.com/cockroachdb/cockroachdb-todo-apps), will they be able to figure out how the directories are linked? Or would it be easier for them to click into the C# directory and find all related things there?

**Comment by mmutiso** [comment]
Having to figure out if the directories are linked presents some mental burden to a new user.

**Comment by Amruta-Ranade** [comment]
right, so let's have one directory then :)

**Comment by mmutiso** [comment]
Cool, look out for a PR in a couple of hours then.

**Comment by mmutiso** [comment]
This was merged. Closing the issue.
